### ISSUE TITLE
Невозможно загрузить годовые отчеты из-за ограничения размера (Уралсиб)

### ISSUE THREAD

**Issue by CyberRSR** [vananiev/portfolio#28]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Apr 27 14:51:57 YEKT 2020
There was an unexpected error (type=Internal Server Error, status=500).
Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.impl.FileSizeLimitExceededException: The field reports exceeds its maximum permitted size of 1048576 bytes.

**Comment by vananiev** [comment]
Размер ваших отчетов больше 1 МБ?

**Comment by vananiev** [comment]
Увеличил до 128 МБ, если не хватит отпишитесь, переоткрою заявку.

**Comment by vananiev** [comment]
До выхода релиза добавьте в файл `portfolio-conf.properties`, который лежит в папке приложения строчки
```
spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB
```
Отчеты начнут загружаться.
