### ISSUE TITLE
Выбор периода для выгрузки

### ISSUE THREAD

**Issue by Alex5545** [vananiev/portfolio#29]
Реализовать в веб-интерфейсе по адресу http://localhost выбор периода времени (либо в виде календаря, где указывается дата начала и конца интересующего периода, либо, чтобы пользователь вводил в специально отведенные поля даты в формате дд.мм.гггг) для выгрузки данных из отчетов в Excel

**Comment by vananiev** [comment]
Допустим есть транзакции по бумаге
| Дата     | Куплено |Продано|
|---------|----------|---------|
| 1.2.2020| 10         |-
| 2.2.2020| -           |2
| 3.2.2020| 1           |-
Допустим дата закрытия реестра 4.2.2020, пришли дивиденды в размере по 10 рублей на каждую бумагу, итого 90 рублей.

Если формировать аналитику за весь период будет 3 транзакции
| Дата открытия | Количество | Дата закрытия  | Дивиденды | Прибыль |
|------------------|-------------|-----------------|--------------|-----------|
| 1.2.2020            | 2                 |2.2.2020            | 20                | xxx           |
| 1.2.2020            | 8                 |                         | 80                 |                |
| 3.2.2020            | 1                 |                         | 10                 |                |

Если формировать аналитику в период с 2.2.2020 - 10.2.2020 как должна выглядеть таблица? Потому что, если не учитывать транзакции до 2.2.2020 будет так:
| Дата открытия  | Количество | Дата закрытия  | Дивиденды | Прибыль |
|------------------|-------------|------------------|--------------|-----------|
| 2.2.2020            | -1                 |3.2.2020            | ???              | ???           |
| 2.2.2020            | -1                 |                         | ???               |                |

где непонятно как раскидывать дивиденды и считать доходность, т.к. правило first input first output соблюсти невозможно.

**Comment by Alex5545** [comment]
Тогда предлагаю именно если делается не запрос всей истории, а частично, то фиксировать только финансовые результаты (т.е. прибыль/убыток) А полный функционал будет только для всей истории. Я Вашу проблему понял и согласен, что метод FIFO сложно применить для качественного анализа. Если вы считаете, что второй вариант неуместен (т.е. двойной функционал), то можете снять вопрос с повестки дня.

**Comment by vananiev** [comment]
Можно еще так, рассчитывать всю историю, но выводить только те сделки, которым дата открытия или дата закрытия попадает в выбранный диапазон. Для примера выше при выборе периода с 2.2.2020 - 10.2.2020 будет отбражаться
| Дата открытия | Количество | Дата закрытия  | Дивиденды | Прибыль |
|------------------|-------------|-----------------|--------------|-----------|
| 1.2.2020            | 2                 |2.2.2020            | 20                | xxx           |
| 3.2.2020            | 1                 |                         | 10                 |                |

Тогда сумма дивидендов, конечно, не совпадет с 90 рублями. Как такой вариант?

Кстати, такой подход будет применим для всех таблиц, за исключением таблицы доходности. Если в таблице доходности не отображать все вводы-выводы ДС, то итоговое сальдо движений ДС за период некорректно сравнивать с текущей стоимостью активов портфеля.

**Comment by Alex5545** [comment]
И дея хорошая, только при релизе для понимания надо сделать указания на это все.

**Comment by vananiev** [comment]
ОК. Тогда запланирую в таком варианте.

**Comment by vananiev** [comment]
@Alex5545, а что если средствами Excel фильтровать, я мог бы добавить фильтры к заголовкам таблиц. Тогда можно будет строить достаточно сложные условия, например,
1. Найти бумаги купленные в марте-мае 2019 г и проданные в декабре 2019 г.
1. То же самое плюс условие стоимости покупки больше 10 т.р.
и т.д.

Как думаешь, это будет лучше?

**Comment by Alex5545** [comment]
С одной стороны лучше, а с другой хуже. Лучше, то что в каком-то плане проще, а с другой цель программы автоматизировать учет, а не самому все высчитывать разницу между декабрем и маем. Я может сказал бы, что точно лучше, если был бы конкретный пример, а не абстракция.

**Comment by vananiev** [comment]
Сделаю к следующему релизу, посмотрите.

**Comment by vananiev** [comment]
Фикс выйдет в 2020.5. Если реализация не устроит, пожалуйста, отпишитесь.
