### ISSUE TITLE
Объединить активы TOD и TOM на валютном рынке

### ISSUE THREAD

**Issue by CyberRSR** [vananiev/portfolio#35]
Например USDRUB_TOM и USDRUB_TOD объединить при подсчете прибыли. Если покупки были в TOD, а продажи в TOM, например.

**Comment by vananiev** [comment]
Логично, можно примеры отчетов в личку.

**Comment by vananiev** [comment]
Можно в таблицу security сохранять ticker = USDRUB_TOM или USDRUB_TOD, а в isin = USDRUB для обоих случаев.

**Comment by CyberRSR** [comment]
[br.zip](https://github.com/vananiev/portfolio/files/4601373/br.zip)

**Comment by vananiev** [comment]
Спасибо.

**Comment by vananiev** [comment]
Сделки на валютной секции вынесены в отдельную таблицы для удобства анализа.
