### ISSUE TITLE
Ссылка на главную страницу после загрузки отчётов.

### ISSUE THREAD

**Issue by MBogda** [vananiev/portfolio#36]
v 2020.4
После загрузки отчётов появляется сообщение: ok, и больше ничего. Для перехода на главную нужно 2 раза нажимать кнопку "Назад" в браузере.
Хочется иметь возможность перейти на главную страницу в один клик.
А ещё лучше - автоматически переходить на главную страницу, предусмотрев на ней место для полученного сообщения по результатам загрузки отчётов. Т.е. после загрузки сразу открывается главная страница с пунктами меню, и там же есть места для системного сообщения, в котором написано "отчёты успешно загружены" или сообщение об ошибке.
Будет полезно, т.к. избавит пользователей от лишних кликов после загрузки отчётов.

Также нужно будет соответствующее изменение в документации

**Comment by vananiev** [comment]
Сделаем.

**Comment by vananiev** [comment]
Вы бы не хотели сами сделать эту фичу? Она простая. Ошибку на главной странице выводить считаю плохо, не совсем понятно будет. В будущем предполагается полноценный локальный  сайт как у интелинвест сделать. Нужен фронтэндер.

А пока предлагаю сделать просто, заменить текст ok на
```
Отчеты загружены [ok]
```
где `ok` будет ссылаться на главную страницу.

**Comment by MBogda** [comment]
Да, готов сделать, фича действительно простая)

**Comment by MBogda** [comment]
Нет прав на создание веток:
```
$ git push --set-upstream origin feature-add-link
remote: Permission to vananiev/portfolio.git denied to MBogda.
fatal: unable to access 'https://github.com/vananiev/portfolio.git/': The requested URL returned error: 403
```

**Comment by vananiev** [comment]
github не дает создавать ветки, нужно клонировать репозиторийв свой профиль, сделать там ветку и предложить pull request. Вот [здесь](https://git-scm.com/book/ru/v2/GitHub-%D0%92%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BE%D0%B1%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%B0-%D0%B2-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%8B) описан процесс. Он един для всех проектов на github. Научившись на моем проекте, сможешь помогать любому другому.

**Comment by MBogda** [comment]
Спасибо за пояснение, раньше почти не коммитил в опенсорс на гитхабе, поэтому думал, тут устроено как в корпоративных аккаунтах: закрытые master/develop/другие существенные вещи, а добавить ветку и создать ПР на влитие в основную ветку может кто угодно.
С одной стороны влитие кода через создание форка выглядит громоздко, хотя с другой. это защищает владельца от кучи мусорных веток, дыр в настройках прав и т.п.
А как обычно приглашаются люди для совместной разработки через Settings -> Invite a collaborator? После проверки, что человек адекватный и внёс большой вклад через схему с форками, или вообще приглашаются только в исключительных случаях?)

Ещё я не понял, как сделать, чтобы в Linked pull requests справа отображался мой ПР.

**Comment by vananiev** [comment]
> А как обычно приглашаются люди для совместной разработки через Settings -> Invite a collaborator

Или pull request или так. pull request'ы позволяют гарантировать проверку кода перед заливкой. Поэтому безопаснее.

> Ещё я не понял, как сделать, чтобы в Linked pull requests справа отображался мой ПР.

Нужно в pull rquest указать номер заявки В последней строчке первого комментария вот так `Closes gh-36`, ссылка формируется сама. Я поменял в pull requeste для наглядности.
