### ISSUE TITLE
Обработка сделок Уралсиб Брокера на срочном рынке

### ISSUE THREAD

**Issue by vananiev** [vananiev/portfolio#4]
Реализовать загрузка из отчета информации о:
- сделках на срочном рынке (интрадей/с переносом позиции, купля/продажа/экспирация);
- ежедневном изменении вариационной маржи.

**Comment by vananiev** [comment]
Нужны примеры ответов

**Comment by CyberRSR** [comment]
дневные отчеты со сделками на срочном рынке
[brok_rpt_.zip](https://github.com/vananiev/portfolio/files/4538943/brok_rpt_.zip)

**Comment by vananiev** [comment]
Спасибо, взял в работу.
