### ISSUE TITLE
Опечатка в инструкции.

### ISSUE THREAD

**Issue by Alex5545** [vananiev/portfolio#47]
В третьем пункте инструкции по установке имеется опечатка.

**Comment by Alex5545** [comment]
Также предлагаю такую редакцию файла README
Назначение

Приложение формирует аналитический обзор финансовых портфелей. Вся информация о финансовом портфеле хранится и обрабатывается локально, подключение к интернету не требуется.
Установка

    Скачать со страницы проекта архив portfolio.zip и распаковать в любую удобную папку.
    Скачать Java 14 и распаковать из архива папку jdk-14 в C:\Program Files\Java\.

Подробная инструкция по установке и запуску приложения для операционных систем Windows и Linux.
Работа с приложением

Запустите файл start.bat, в браузере перейдите по адресу http://localhost и загрузите отчеты брокера.

Для удобства приложение допускает:

    Многократную загрузку одного и того же отчета (полезно, если вы не помните, загрузили конкретный отчет или нет), дублирования данных не произойдет.
    Загрузку отчетов за любой временной интервал (день, месяц, год или др). Причем, /допустимо, что отчеты разных временных периодов будут перекрываться.
    Допустимо загружать отчеты по нескольким брокерским/инвестиционным счетам, в том числе от разных брокерских домов.

После загрузки отчета становится доступным аналитическая выгрузка по вашим портфелям в формате excel файла:

    доходность сделок на фондовом рынке; stock-market
    доходность сделок на срочном рынке; derivatives-market
    пополнения, списания и доходность портфеля; cash-in
    налоговая нагрузка. tax

Для корректного учета выплат по ценным бумагам (дивидендов, купонов, амортизации облигаций) рекомендуется загружать в приложение все сделки (не пропускать отчеты брокера). Если информация о количестве ценных бумаг, которой обладает приложение, отличается от количества бумаг, по которым произведена выплата, то при формировании аналитической выгрузки приложение сообщит об ошибке в лог portfolio.log.
Обновление приложения

Скачать со станицы проекта архив portfolio.zip и распаковать в любую удобную папку. Приложение готово к запуску файлом start.bat.
Документация

Дополнительная информация может быть найдена в документации.

**Comment by vananiev** [comment]
Спасибо, исправим.
